const countryNames = [
    "España",
    "Pakistán",
    "India",
    "Bangladesh",
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antártida",
    "Antigua y Barbuda",
    "Antillas Holandesas",
    "Arabia Saudita",
    "Argelia",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaiján",
    "Bahamas",
    "Bahrain",
    "Barbados",
    "Bélgica",
    "Belice",
    "Benin",
    "Bhutan",
    "Bielorusia",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brasil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Colombia",
    "Comoros",
    "Congo",
    "Corea del Norte",
    "Corea del Sur",
    "Costa de Marfil",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Darussalam",
    "Dinamarca",
    "Djibouti",
    "Dominica",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Em. Arabes Un.",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "Estados Unidos",
    "Estonia",
    "Etiopía",
    "Fiji",
    "Filipinas",
    "Finlandia",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Ghana",
    "Gibraltar",
    "Grecia",
    "Grenada",
    "Groenlandia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guayana Francesa",
    "Guinea",
    "Guinea Ecuatorial",
    "Guinea-Bissau",
    "Guyana",
    "Haití",
    "Holanda",
    "Honduras",
    "Hong Kong",
    "Hungría",
    "Indonesia",
    "Irak",
    "Irán",
    "Irlanda",
    "Islandia",
    "Islas Cayman",
    "Islas Cook",
    "Islas Faroe",
    "Islas Marianas del Norte",
    "Islas Marshall",
    "Islas Solomon",
    "Islas Turcas y Caicos",
    "Islas Vírgenes",
    "Islas Wallis y Futuna",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jordania",
    "Kazajstán",
    "Kenya",
    "Kirguistán",
    "Kiribati",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Letonia",
    "Líbano",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Macao",
    "Macedonia",
    "Madagascar",
    "Malasia",
    "Malawi",
    "Mali",
    "Malta",
    "Marruecos",
    "Martinica",
    "Mauricio",
    "Mauritania",
    "Mayotte",
    "México",
    "Micronesia",
    "Moldova",
    "Mónaco",
    "Mongolia",
    "Montserrat",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Níger",
    "Nigeria",
    "Noruega",
    "Nueva Caledonia",
    "Nueva Zelandia",
    "Omán",
    "Panamá",
    "Papua Nueva Guinea",
    "Paraguay",
    "Perú",
    "Pitcairn",
    "Polinesia Francesa",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "RD Congo",
    "Reino Unido",
    "República Centroafricana",
    "República Checa",
    "República Dominicana",
    "Reunión",
    "Rumania",
    "Rusia",
    "Rwanda",
    "Sahara Occidental",
    "Saint Pierre y Miquelon",
    "Samoa",
    "Samoa Americana",
    "San Cristóbal y Nevis",
    "San Marino",
    "Santa Elena",
    "Santa Lucía",
    "Sao Tomé y Príncipe",
    "Senegal",
    "Serbia y Montenegro",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Siria",
    "Somalia",
    "Sri Lanka",
    "Sudáfrica",
    "Sudán",
    "Suecia",
    "Suiza",
    "Suriname",
    "Swazilandia",
    "Taiwán",
    "Uruguay"
];

export default countryNames;
