const countryNames = [
    { key: "España", text: "España" },
    { key: "Pakistán", text: "Pakistán" },
    { key: "India", text: "India" },
    { key: "Bangladesh", text: "Bangladesh" },
    { key: "Afganistán", text: "Afganistán" },
    { key: "Albania", text: "Albania" },
    { key: "Alemania", text: "Alemania" },
    { key: "Andorra", text: "Andorra" },
    { key: "Angola", text: "Angola" },
    { key: "Anguilla", text: "Anguilla" },
    { key: "Antártida", text: "Antártida" },
    { key: "Antigua y Barbuda", text: "Antigua y Barbuda" },
    { key: "Antillas Holandesas", text: "Antillas Holandesas" },
    { key: "Arabia Saudita", text: "Arabia Saudita" },
    { key: "Argelia", text: "Argelia" },
    { key: "Argentina", text: "Argentina" },
    { key: "Armenia", text: "Armenia" },
    { key: "Aruba", text: "Aruba" },
    { key: "Australia", text: "Australia" },
    { key: "Austria", text: "Austria" },
    { key: "Azerbaiján", text: "Azerbaiján" },
    { key: "Bahamas", text: "Bahamas" },
    { key: "Bahrain", text: "Bahrain" },
    { key: "Barbados", text: "Barbados" },
    { key: "Bélgica", text: "Bélgica" },
    { key: "Belice", text: "Belice" },
    { key: "Benin", text: "Benin" },
    { key: "Bhutan", text: "Bhutan" },
    { key: "Bielorusia", text: "Bielorusia" },
    { key: "Bolivia", text: "Bolivia" },
    { key: "Bosnia Herzegovina", text: "Bosnia Herzegovina" },
    { key: "Botswana", text: "Botswana" },
    { key: "Brasil", text: "Brasil" },
    { key: "Brunei", text: "Brunei" },
    { key: "Bulgaria", text: "Bulgaria" },
    { key: "Burkina Faso", text: "Burkina Faso" },
    { key: "Burundi", text: "Burundi" },
    { key: "Cabo Verde", text: "Cabo Verde" },
    { key: "Camboya", text: "Camboya" },
    { key: "Camerún", text: "Camerún" },
    { key: "Canadá", text: "Canadá" },
    { key: "Chad", text: "Chad" },
    { key: "Chile", text: "Chile" },
    { key: "China", text: "China" },
    { key: "Chipre", text: "Chipre" },
    { key: "Colombia", text: "Colombia" },
    { key: "Comoros", text: "Comoros" },
    { key: "Congo", text: "Congo" },
    { key: "Corea del Norte", text: "Corea del Norte" },
    { key: "Corea del Sur", text: "Corea del Sur" },
    { key: "Costa de Marfil", text: "Costa de Marfil" },
    { key: "Costa Rica", text: "Costa Rica" },
    { key: "Croacia", text: "Croacia" },
    { key: "Cuba", text: "Cuba" },
    { key: "Darussalam", text: "Darussalam" },
    { key: "Dinamarca", text: "Dinamarca" },
    { key: "Djibouti", text: "Djibouti" },
    { key: "Dominica", text: "Dominica" },
    { key: "Ecuador", text: "Ecuador" },
    { key: "Egipto", text: "Egipto" },
    { key: "El Salvador", text: "El Salvador" },
    { key: "Em. Arabes Un.", text: "Em. Arabes Un." },
    { key: "Eritrea", text: "Eritrea" },
    { key: "Eslovaquia", text: "Eslovaquia" },
    { key: "Eslovenia", text: "Eslovenia" },
    { key: "Estados Unidos", text: "Estados Unidos" },
    { key: "Estonia", text: "Estonia" },
    { key: "Etiopía", text: "Etiopía" },
    { key: "Fiji", text: "Fiji" },
    { key: "Filipinas", text: "Filipinas" },
    { key: "Finlandia", text: "Finlandia" },
    { key: "Francia", text: "Francia" },
    { key: "Gabón", text: "Gabón" },
    { key: "Gambia", text: "Gambia" },
    { key: "Georgia", text: "Georgia" },
    { key: "Ghana", text: "Ghana" },
    { key: "Gibraltar", text: "Gibraltar" },
    { key: "Grecia", text: "Grecia" },
    { key: "Grenada", text: "Grenada" },
    { key: "Groenlandia", text: "Groenlandia" },
    { key: "Guadalupe", text: "Guadalupe" },
    { key: "Guam", text: "Guam" },
    { key: "Guatemala", text: "Guatemala" },
    { key: "Guayana Francesa", text: "Guayana Francesa" },
    { key: "Guinea", text: "Guinea" },
    { key: "Guinea Ecuatorial", text: "Guinea Ecuatorial" },
    { key: "Guinea-Bissau", text: "Guinea-Bissau" },
    { key: "Guyana", text: "Guyana" },
    { key: "Haití", text: "Haití" },
    { key: "Holanda", text: "Holanda" },
    { key: "Honduras", text: "Honduras" },
    { key: "Hong Kong", text: "Hong Kong" },
    { key: "Hungría", text: "Hungría" },
    { key: "Indonesia", text: "Indonesia" },
    { key: "Irak", text: "Irak" },
    { key: "Irán", text: "Irán" },
    { key: "Irlanda", text: "Irlanda" },
    { key: "Islandia", text: "Islandia" },
    { key: "Islas Cayman", text: "Islas Cayman" },
    { key: "Islas Cook", text: "Islas Cook" },
    { key: "Islas Faroe", text: "Islas Faroe" },
    { key: "Islas Marianas del Norte", text: "Islas Marianas del Norte" },
    { key: "Islas Marshall", text: "Islas Marshall" },
    { key: "Islas Solomon", text: "Islas Solomon" },
    { key: "Islas Turcas y Caicos", text: "Islas Turcas y Caicos" },
    { key: "Islas Vírgenes", text: "Islas Vírgenes" },
    { key: "Islas Wallis y Futuna", text: "Islas Wallis y Futuna" },
    { key: "Israel", text: "Israel" },
    { key: "Italia", text: "Italia" },
    { key: "Jamaica", text: "Jamaica" },
    { key: "Japón", text: "Japón" },
    { key: "Jordania", text: "Jordania" },
    { key: "Kazajstán", text: "Kazajstán" },
    { key: "Kenya", text: "Kenya" },
    { key: "Kirguistán", text: "Kirguistán" },
    { key: "Kiribati", text: "Kiribati" },
    { key: "Kuwait", text: "Kuwait" },
    { key: "Laos", text: "Laos" },
    { key: "Lesotho", text: "Lesotho" },
    { key: "Letonia", text: "Letonia" },
    { key: "Líbano", text: "Líbano" },
    { key: "Liberia", text: "Liberia" },
    { key: "Libia", text: "Libia" },
    { key: "Liechtenstein", text: "Liechtenstein" },
    { key: "Lituania", text: "Lituania" },
    { key: "Luxemburgo", text: "Luxemburgo" },
    { key: "Macao", text: "Macao" },
    { key: "Macedonia", text: "Macedonia" },
    { key: "Madagascar", text: "Madagascar" },
    { key: "Malasia", text: "Malasia" },
    { key: "Malawi", text: "Malawi" },
    { key: "Mali", text: "Mali" },
    { key: "Malta", text: "Malta" },
    { key: "Marruecos", text: "Marruecos" },
    { key: "Martinica", text: "Martinica" },
    { key: "Mauricio", text: "Mauricio" },
    { key: "Mauritania", text: "Mauritania" },
    { key: "Mayotte", text: "Mayotte" },
    { key: "México", text: "México" },
    { key: "Micronesia", text: "Micronesia" },
    { key: "Moldova", text: "Moldova" },
    { key: "Mónaco", text: "Mónaco" },
    { key: "Mongolia", text: "Mongolia" },
    { key: "Montserrat", text: "Montserrat" },
    { key: "Mozambique", text: "Mozambique" },
    { key: "Myanmar", text: "Myanmar" },
    { key: "Namibia", text: "Namibia" },
    { key: "Nauru", text: "Nauru" },
    { key: "Nepal", text: "Nepal" },
    { key: "Nicaragua", text: "Nicaragua" },
    { key: "Níger", text: "Níger" },
    { key: "Nigeria", text: "Nigeria" },
    { key: "Noruega", text: "Noruega" },
    { key: "Nueva Caledonia", text: "Nueva Caledonia" },
    { key: "Nueva Zelandia", text: "Nueva Zelandia" },
    { key: "Omán", text: "Omán" },
    { key: "Panamá", text: "Panamá" },
    { key: "Papua Nueva Guinea", text: "Papua Nueva Guinea" },
    { key: "Paraguay", text: "Paraguay" },
    { key: "Perú", text: "Perú" },
    { key: "Pitcairn", text: "Pitcairn" },
    { key: "Polinesia Francesa", text: "Polinesia Francesa" },
    { key: "Polonia", text: "Polonia" },
    { key: "Portugal", text: "Portugal" },
    { key: "Puerto Rico", text: "Puerto Rico" },
    { key: "Qatar", text: "Qatar" },
    { key: "RD Congo", text: "RD Congo" },
    { key: "Reino Unido", text: "Reino Unido" },
    { key: "República Centroafricana", text: "República Centroafricana" },
    { key: "República Checa", text: "República Checa" },
    { key: "República Dominicana", text: "República Dominicana" },
    { key: "Reunión", text: "Reunión" },
    { key: "Rumania", text: "Rumania" },
    { key: "Rusia", text: "Rusia" },
    { key: "Rwanda", text: "Rwanda" },
    { key: "Sahara Occidental", text: "Sahara Occidental" },
    { key: "Saint Pierre y Miquelon", text: "Saint Pierre y Miquelon" },
    { key: "Samoa", text: "Samoa" },
    { key: "Samoa Americana", text: "Samoa Americana" },
    { key: "San Cristóbal y Nevis", text: "San Cristóbal y Nevis" },
    { key: "San Marino", text: "San Marino" },
    { key: "Santa Elena", text: "Santa Elena" },
    { key: "Santa Lucía", text: "Santa Lucía" },
    { key: "Sao Tomé y Príncipe", text: "Sao Tomé y Príncipe" },
    { key: "Senegal", text: "Senegal" },
    { key: "Serbia y Montenegro", text: "Serbia y Montenegro" },
    { key: "Seychelles", text: "Seychelles" },
    { key: "Sierra Leona", text: "Sierra Leona" },
    { key: "Singapur", text: "Singapur" },
    { key: "Siria", text: "Siria" },
    { key: "Somalia", text: "Somalia" },
    { key: "Sri Lanka", text: "Sri Lanka" },
    { key: "Sudáfrica", text: "Sudáfrica" },
    { key: "Sudán", text: "Sudán" },
    { key: "Suecia", text: "Suecia" },
    { key: "Suiza", text: "Suiza" },
    { key: "Suriname", text: "Suriname" },
    { key: "Swazilandia", text: "Swazilandia" },
    { key: "Taiwán", text: "Taiwán" },
    { key: "Uruguay", text: "Uruguay" }
];

export default countryNames;
