const spanishCityNames = [
    "Barcelona",
    "L’Hospitalet de Llobregat",
    "Badalona",
    "Cornellà",
    "Sabadell",
    "Terrassa",
    "Vilanova i la Geltrú",
    "Ávila",
    "A Coruña",
    "Albacete",
    "Alcalá de Guadaira",
    "Alcalá de Henares",
    "Alcoy",
    "Alcántara",
    "Alcázar de San Juan",
    "Algeciras",
    "Alicante",
    "Almadén",
    "Almendralejo",
    "Almería",
    "Alzira",
    "Andújar",
    "Antequera",
    "Aranjuez",
    "Arcos de la Frontera",
    "Arucas",
    "Astorga",
    "Avilés",
    "Badajoz",
    "Barakaldo",
    "Baza",
    "Bilbao",
    "Bujalance",
    "Burgos",
    "Cabañaquinta",
    "Cabra",
    "Calahorra",
    "Cangas de Narcea",
    "Caravaca",
    "Carballo",
    "Carmona",
    "Cartagena",
    "Castellón de la Plana",
    "Chiclana de la Frontera",
    "Cieza",
    "Ciudad Real",
    "Ciudad Rodrigo",
    "Covadonga",
    "Coín",
    "Cuenca",
    "Cáceres",
    "Cádiz",
    "Córdoba",
    "Don Benito",
    "Donostia–San Sebastián",
    "Dos Hermanas",
    "Ecija",
    "Eibar",
    "El Escorial",
    "El Puerto de Santa María",
    "Elche",
    "Elda",
    "Ferrol",
    "Funes",
    "Gandía",
    "Getafe",
    "Getxo",
    "Gijón",
    "Girona",
    "Granada",
    "Granollers",
    "Guadalajara",
    "Guadalupe",
    "Guadix",
    "Guernica",
    "Hellín",
    "Huelva",
    "Huesca",
    "Irun",
    "Jaca",
    "Jaén",
    "Jerez de la Frontera",
    "Jumilla",
    "La Línea",
    "La Orotava",
    "Las Palmas",
    "Lebrija",
    "León",
    "Linares",
    "Lleida",
    "Llívia",
    "Logroño",
    "Lora del Río",
    "Lorca",
    "Luarca",
    "Lucena",
    "Lugo",
    "Madrid",
    "Manresa",
    "Marchena",
    "Martos",
    "Mataró",
    "Maó",
    "Melilla",
    "Mieres",
    "Miranda de Ebro",
    "Mondoñedo",
    "Monforte de Lemos",
    "Montilla",
    "Morón de la Frontera",
    "Motril",
    "Murcia",
    "Málaga",
    "Mérida",
    "Orihuela",
    "Ortigueira",
    "Osuna",
    "Ourense",
    "Oviedo",
    "Palencia",
    "Palma",
    "Pamplona",
    "Peñarroya-Pueblonuevo",
    "Plasencia",
    "Pola de Siero",
    "Ponferrada",
    "Pontevedra",
    "Portugalete",
    "Priego de Córdoba",
    "Puente-Genil",
    "Puerto Real",
    "Puertollano",
    "Requena",
    "Reus",
    "Ribeira",
    "Roncesvalles",
    "Ronda",
    "Sagunto",
    "Salamanca",
    "San Fernando",
    "San Ildefonso",
    "San Martín del Rey Aurelio",
    "Sanlúcar de Barrameda",
    "Santa Coloma de Gramenet",
    "Santa Cruz de Tenerife",
    "Santander",
    "Santiago de Compostela",
    "Santurtzi",
    "Segovia",
    "Sestao",
    "Sevilla",
    "Simancas",
    "Soria",
    "Sueca",
    "Talavera de la Reina",
    "Tarragona",
    "Telde",
    "Teruel",
    "Tineo",
    "Toledo",
    "Tomelloso",
    "Toro",
    "Torrelavega",
    "Torrent",
    "Tortosa",
    "Trujillo",
    "Úbeda",
    "Utrera",
    "Valdepeñas",
    "Valencia",
    "Valladolid",
    "Vic",
    "Vigo",
    "Vilagarcía de Arousa",
    "Vilalba",
    "Villanueva de la Serena",
    "Villarreal",
    "Villarrobledo",
    "Villaviciosa",
    "Villena",
    "Vitoria-Gasteiz",
    "Yecla",
    "Zamora",
    "Zaragoza",
];
export default spanishCityNames;