const spanishCityNames = [
    { key: "Barcelona", text: "Barcelona" },
    { key: "L’Hospitalet de Llobregat", text: "L’Hospitalet de Llobregat" },
    { key: "Badalona", text: "Badalona" },
    { key: "Cornellà", text: "Cornellà" },
    { key: "Sabadell", text: "Sabadell" },
    { key: "Terrassa", text: "Terrassa" },
    { key: "Vilanova i la Geltrú", text: "Vilanova i la Geltrú" },
    { key: "Ávila", text: "Ávila" },
    { key: "A Coruña", text: "A Coruña" },
    { key: "Albacete", text: "Albacete" },
    { key: "Alcalá de Guadaira", text: "Alcalá de Guadaira" },
    { key: "Alcalá de Henares", text: "Alcalá de Henares" },
    { key: "Alcoy", text: "Alcoy" },
    { key: "Alcántara", text: "Alcántara" },
    { key: "Alcázar de San Juan", text: "Alcázar de San Juan" },
    { key: "Algeciras", text: "Algeciras" },
    { key: "Alicante", text: "Alicante" },
    { key: "Almadén", text: "Almadén" },
    { key: "Almendralejo", text: "Almendralejo" },
    { key: "Almería", text: "Almería" },
    { key: "Alzira", text: "Alzira" },
    { key: "Andújar", text: "Andújar" },
    { key: "Antequera", text: "Antequera" },
    { key: "Aranjuez", text: "Aranjuez" },
    { key: "Arcos de la Frontera", text: "Arcos de la Frontera" },
    { key: "Arucas", text: "Arucas" },
    { key: "Astorga", text: "Astorga" },
    { key: "Avilés", text: "Avilés" },
    { key: "Badajoz", text: "Badajoz" },
    { key: "Barakaldo", text: "Barakaldo" },
    { key: "Baza", text: "Baza" },
    { key: "Bilbao", text: "Bilbao" },
    { key: "Bujalance", text: "Bujalance" },
    { key: "Burgos", text: "Burgos" },
    { key: "Cabañaquinta", text: "Cabañaquinta" },
    { key: "Cabra", text: "Cabra" },
    { key: "Calahorra", text: "Calahorra" },
    { key: "Cangas de Narcea", text: "Cangas de Narcea" },
    { key: "Caravaca", text: "Caravaca" },
    { key: "Carballo", text: "Carballo" },
    { key: "Carmona", text: "Carmona" },
    { key: "Cartagena", text: "Cartagena" },
    { key: "Castellón de la Plana", text: "Castellón de la Plana" },
    { key: "Chiclana de la Frontera", text: "Chiclana de la Frontera" },
    { key: "Cieza", text: "Cieza" },
    { key: "Ciudad Real", text: "Ciudad Real" },
    { key: "Ciudad Rodrigo", text: "Ciudad Rodrigo" },
    { key: "Covadonga", text: "Covadonga" },
    { key: "Coín", text: "Coín" },
    { key: "Cuenca", text: "Cuenca" },
    { key: "Cáceres", text: "Cáceres" },
    { key: "Cádiz", text: "Cádiz" },
    { key: "Córdoba", text: "Córdoba" },
    { key: "Don Benito", text: "Don Benito" },
    { key: "Donostia–San Sebastián", text: "Donostia–San Sebastián" },
    { key: "Dos Hermanas", text: "Dos Hermanas" },
    { key: "Ecija", text: "Ecija" },
    { key: "Eibar", text: "Eibar" },
    { key: "El Escorial", text: "El Escorial" },
    { key: "El Puerto de Santa María", text: "El Puerto de Santa María" },
    { key: "Elche", text: "Elche" },
    { key: "Elda", text: "Elda" },
    { key: "Ferrol", text: "Ferrol" },
    { key: "Funes", text: "Funes" },
    { key: "Gandía", text: "Gandía" },
    { key: "Getafe", text: "Getafe" },
    { key: "Getxo", text: "Getxo" },
    { key: "Gijón", text: "Gijón" },
    { key: "Girona", text: "Girona" },
    { key: "Granada", text: "Granada" },
    { key: "Granollers", text: "Granollers" },
    { key: "Guadalajara", text: "Guadalajara" },
    { key: "Guadalupe", text: "Guadalupe" },
    { key: "Guadix", text: "Guadix" },
    { key: "Guernica", text: "Guernica" },
    { key: "Hellín", text: "Hellín" },
    { key: "Huelva", text: "Huelva" },
    { key: "Huesca", text: "Huesca" },
    { key: "Irun", text: "Irun" },
    { key: "Jaca", text: "Jaca" },
    { key: "Jaén", text: "Jaén" },
    { key: "Jerez de la Frontera", text: "Jerez de la Frontera" },
    { key: "Jumilla", text: "Jumilla" },
    { key: "La Línea", text: "La Línea" },
    { key: "La Orotava", text: "La Orotava" },
    { key: "Las Palmas", text: "Las Palmas" },
    { key: "Lebrija", text: "Lebrija" },
    { key: "León", text: "León" },
    { key: "Linares", text: "Linares" },
    { key: "Lleida", text: "Lleida" },
    { key: "Llívia", text: "Llívia" },
    { key: "Logroño", text: "Logroño" },
    { key: "Lora del Río", text: "Lora del Río" },
    { key: "Lorca", text: "Lorca" },
    { key: "Luarca", text: "Luarca" },
    { key: "Lucena", text: "Lucena" },
    { key: "Lugo", text: "Lugo" },
    { key: "Madrid", text: "Madrid" },
    { key: "Manresa", text: "Manresa" },
    { key: "Marchena", text: "Marchena" },
    { key: "Martos", text: "Martos" },
    { key: "Mataró", text: "Mataró" },
    { key: "Maó", text: "Maó" },
    { key: "Melilla", text: "Melilla" },
    { key: "Mieres", text: "Mieres" },
    { key: "Miranda de Ebro", text: "Miranda de Ebro" },
    { key: "Mondoñedo", text: "Mondoñedo" },
    { key: "Monforte de Lemos", text: "Monforte de Lemos" },
    { key: "Montilla", text: "Montilla" },
    { key: "Morón de la Frontera", text: "Morón de la Frontera" },
    { key: "Motril", text: "Motril" },
    { key: "Murcia", text: "Murcia" },
    { key: "Málaga", text: "Málaga" },
    { key: "Mérida", text: "Mérida" },
    { key: "Orihuela", text: "Orihuela" },
    { key: "Ortigueira", text: "Ortigueira" },
    { key: "Osuna", text: "Osuna" },
    { key: "Ourense", text: "Ourense" },
    { key: "Oviedo", text: "Oviedo" },
    { key: "Palencia", text: "Palencia" },
    { key: "Palma", text: "Palma" },
    { key: "Pamplona", text: "Pamplona" },
    { key: "Peñarroya-Pueblonuevo", text: "Peñarroya-Pueblonuevo" },
    { key: "Plasencia", text: "Plasencia" },
    { key: "Pola de Siero", text: "Pola de Siero" },
    { key: "Ponferrada", text: "Ponferrada" },
    { key: "Pontevedra", text: "Pontevedra" },
    { key: "Portugalete", text: "Portugalete" },
    { key: "Priego de Córdoba", text: "Priego de Córdoba" },
    { key: "Puente-Genil", text: "Puente-Genil" },
    { key: "Puerto Real", text: "Puerto Real" },
    { key: "Puertollano", text: "Puertollano" },
    { key: "Requena", text: "Requena" },
    { key: "Reus", text: "Reus" },
    { key: "Ribeira", text: "Ribeira" },
    { key: "Roncesvalles", text: "Roncesvalles" },
    { key: "Ronda", text: "Ronda" },
    { key: "Sagunto", text: "Sagunto" },
    { key: "Salamanca", text: "Salamanca" },
    { key: "San Fernando", text: "San Fernando" },
    { key: "San Ildefonso", text: "San Ildefonso" },
    { key: "San Martín del Rey Aurelio", text: "San Martín del Rey Aurelio" },
    { key: "Sanlúcar de Barrameda", text: "Sanlúcar de Barrameda" },
    { key: "Santa Coloma de Gramenet", text: "Santa Coloma de Gramenet" },
    { key: "Santa Cruz de Tenerife", text: "Santa Cruz de Tenerife" },
    { key: "Santander", text: "Santander" },
    { key: "Santiago de Compostela", text: "Santiago de Compostela" },
    { key: "Santurtzi", text: "Santurtzi" },
    { key: "Segovia", text: "Segovia" },
    { key: "Sestao", text: "Sestao" },
    { key: "Sevilla", text: "Sevilla" },
    { key: "Simancas", text: "Simancas" },
    { key: "Soria", text: "Soria" },
    { key: "Sueca", text: "Sueca" },
    { key: "Talavera de la Reina", text: "Talavera de la Reina" },
    { key: "Tarragona", text: "Tarragona" },
    { key: "Telde", text: "Telde" },
    { key: "Teruel", text: "Teruel" },
    { key: "Tineo", text: "Tineo" },
    { key: "Toledo", text: "Toledo" },
    { key: "Tomelloso", text: "Tomelloso" },
    { key: "Toro", text: "Toro" },
    { key: "Torrelavega", text: "Torrelavega" },
    { key: "Torrent", text: "Torrent" },
    { key: "Tortosa", text: "Tortosa" },
    { key: "Trujillo", text: "Trujillo" },
    { key: "Úbeda", text: "Úbeda" },
    { key: "Utrera", text: "Utrera" },
    { key: "Valdepeñas", text: "Valdepeñas" },
    { key: "Valencia", text: "Valencia" },
    { key: "Valladolid", text: "Valladolid" },
    { key: "Vic", text: "Vic" },
    { key: "Vigo", text: "Vigo" },
    { key: "Vilagarcía de Arousa", text: "Vilagarcía de Arousa" },
    { key: "Vilalba", text: "Vilalba" },
    { key: "Villanueva de la Serena", text: "Villanueva de la Serena" },
    { key: "Villarreal", text: "Villarreal" },
    { key: "Villarrobledo", text: "Villarrobledo" },
    { key: "Villaviciosa", text: "Villaviciosa" },
    { key: "Villena", text: "Villena" },
    { key: "Vitoria-Gasteiz", text: "Vitoria-Gasteiz" },
    { key: "Yecla", text: "Yecla" },
    { key: "Zamora", text: "Zamora" },
    { key: "Zaragoza", text: "Zaragoza" }
];
export default spanishCityNames;